### PR TITLE
Exposes `MoleculeView::nuclei()` to Python

### PR DESCRIPTION
**Pull request by ryanmrichard**
**Is this pull request associated with an issue(s)?**
No

**Description**
The `nuclei` part of the `MoleculeView` object was not exposed to Python. This PR exposes it and adds unit tests.

**TODOs**
None. R2g.

### CODE REVIEW

**Comment by ryanmrichard** [comment]
@jlheflin try this.

**Review by jwaldrop107 — APPROVED** [review]

**Comment by jlheflin** [comment]
I recompiled NWChemEx, made sure that it was pointing to a Chemist implementation that used "expose_nuclei" and I am still unable to get the nuclei coordinates. I'll double check again to make sure that this isn't my error though.

**Review by jlheflin — APPROVED** [review]
Nvm didn't remember to change the Chemist source for GhostFragment build. Works and R2g

**Comment by jwaldrop107** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/NWChemEx/Chemist/actions/runs/10801353109) **New version**:[v1.2.9](https://github.com/NWChemEx/Chemist/releases/tag/v1.2.9) **Changes**:[v1.2.8...v1.2.9](https://github.com/NWChemEx/Chemist/compare/v1.2.8...v1.2.9)

**Pull request merged**
